export const CHALLENGE_LIST_REQUEST = "CHALLENGE_LIST_REQUEST";
export const CHALLENGE_LIST_SUCCESS = "CHALLENGE_LIST_SUCCESS";
export const CHALLENGE_LIST_FAIL = "CHALLENGE_LIST_FAIL";

export const CHALLENGE_DETAILS_REQUEST = "CHALLENGE_DETAILS_REQUEST";
export const CHALLENGE_DETAILS_SUCCESS = "CHALLENGE_DETAILS_SUCCESS";
export const CHALLENGE_DETAILS_FAIL = "CHALLENGE_DETAILS_FAIL";

export const CHALLENGE_DELETE_REQUEST = "CHALLENGE_DELETE_REQUEST";
export const CHALLENGE_DELETE_SUCCESS = "CHALLENGE_DELETE_SUCCESS";
export const CHALLENGE_DELETE_FAIL = "CHALLENGE_DELETE_FAIL";

export const CHALLENGE_CREATE_REQUEST = "CHALLENGE_CREATE_REQUEST";
export const CHALLENGE_CREATE_SUCCESS = "CHALLENGE_CREATE_SUCCESS";
export const CHALLENGE_CREATE_FAIL = "CHALLENGE_CREATE_FAIL";
export const CHALLENGE_CREATE_RESET = "CHALLENGE_CREATE_RESET";

export const CHALLENGE_UPDATE_REQUEST = "CHALLENGE_UPDATE_REQUEST";
export const CHALLENGE_UPDATE_SUCCESS = "CHALLENGE_UPDATE_SUCCESS";
export const CHALLENGE_UPDATE_FAIL = "CHALLENGE_UPDATE_FAIL";
export const CHALLENGE_UPDATE_RESET = "CHALLENGE_UPDATE_RESET";
